### ISSUE TITLE
แก้ bug ......ได้ยังไง

### ISSUE THREAD

**Issue by AdisornNon** [AdisornNon/helloTest#2]
หลังจากใช้ software ไปพักนึวเจอ bug ที่.......... จะแก้ไขยังไงครับบ

**Comment by AdisornNon** [comment]
แก้ไขที่โดยเพิ่ม ........... ที่บรรทัด ......................................ลองดูครับ

**Comment by afterprojectz** [comment]
หิดถิ

**Comment by AdisornNon** [comment]
เอาเลยๆ
